import pytest
from unittest.mock import patch, MagicMock
from mainapp.objects.exceptions import (
    DailyFavouriteSpotifyTrackNotFound,
    DailyFavouriteSpotifyInvalidBase62ID,
)
from mainapp.services.spotifyConnector import SpotifyConnector


@pytest.mark.django_db
class TestSpotify:

    @patch("mainapp.services.spotifyConnector.requests.get")
    @patch("mainapp.services.spotifyConnector.requests.post")
    def test_get_track(self, mock_post, mock_get):
        # Mock für access_token
        mock_post.return_value = MagicMock(
            json=lambda: {"access_token": "fake_token"}, raise_for_status=lambda: None
        )

        # Mock für track response
        mock_get.return_value = MagicMock(
            json=lambda: self._get_track_response(), raise_for_status=lambda: None
        )

        track = SpotifyConnector().get_Track("123")

        assert track.name == "2 Sitza"
        assert track.album == "grünewürfelflow"
        assert track.artist == "Pashanim"
        assert (
            track.image_url
            == "https://i.scdn.co/image/ab67616d0000b2739edf8855e6b1b876281d65f1"
        )
        assert track.preview_url is None
        assert track.song_url == "https://open.spotify.com/track/7L3Pw4DFV4vsNOAj08pfCI"

    @patch("mainapp.services.spotifyConnector.requests.get")
    @patch("mainapp.services.spotifyConnector.requests.post")
    def test_track_search(self, mock_post, mock_get):
        mock_post.return_value = MagicMock(
            json=lambda: {"access_token": "fake_token"}, raise_for_status=lambda: None
        )

        mock_get.return_value = MagicMock(
            json=lambda: self._get_search_response(), raise_for_status=lambda: None
        )

        search = SpotifyConnector().search_music_title("Hallo", 3)

        assert isinstance(search, list)
        assert isinstance(search[0], dict)
        assert len(search) == 3
        assert list(search[0].keys()) == ["id", "name", "artist"]

    @patch("mainapp.services.spotifyConnector.requests.get")
    @patch("mainapp.services.spotifyConnector.requests.post")
    @pytest.mark.parametrize(
        "expected_exception, track_id",
        [
            (DailyFavouriteSpotifyTrackNotFound, "11dFghVXANMlKmJX23CbNl"),
            (DailyFavouriteSpotifyInvalidBase62ID, "11fgjmJXsNCbNl"),
        ],
    )
    def test_invalid_track(self, mock_post, mock_get, expected_exception, track_id):
        mock_post.return_value = MagicMock(
            json=lambda: {"access_token": "fake_token"}, raise_for_status=lambda: None
        )

        mock_get.return_value = MagicMock(
            json=lambda: self._get_error_response(expected_exception),
            raise_for_status=lambda: None,
        )

        with pytest.raises(expected_exception):
            SpotifyConnector().get_Track(track_id)

    # Helpers
    def _get_error_response(self, exception):
        if exception is DailyFavouriteSpotifyTrackNotFound:
            return {"error": {"status": 404, "message": "Resource not found"}}
        if exception is DailyFavouriteSpotifyInvalidBase62ID:
            return {"error": {"status": 400, "message": "Invalid base62 id"}}

    def _get_track_response(self):
        return {
            "album": {
                "album_type": "single",
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/34LetYSjEuG2fBb4Z8PwPg"
                        },
                        "href": "https://api.spotify.com/v1/artists/34LetYSjEuG2fBb4Z8PwPg",
                        "id": "34LetYSjEuG2fBb4Z8PwPg",
                        "name": "Pashanim",
                        "type": "artist",
                        "uri": "spotify:artist:34LetYSjEuG2fBb4Z8PwPg",
                    }
                ],
                "available_markets": [
                    "AR",
                    "AU",
                    "AT",
                    "BE",
                    "BO",
                    "BR",
                    "BG",
                    "CA",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DK",
                    "DO",
                    "DE",
                    "EC",
                    "EE",
                    "SV",
                    "FI",
                    "FR",
                    "GR",
                    "GT",
                    "HN",
                    "HK",
                    "HU",
                    "IS",
                    "IE",
                    "IT",
                    "LV",
                    "LT",
                    "LU",
                    "MY",
                    "MT",
                    "MX",
                    "NL",
                    "NZ",
                    "NI",
                    "NO",
                    "PA",
                    "PY",
                    "PE",
                    "PH",
                    "PL",
                    "PT",
                    "SG",
                    "SK",
                    "ES",
                    "SE",
                    "CH",
                    "TW",
                    "TR",
                    "UY",
                    "US",
                    "GB",
                    "AD",
                    "LI",
                    "MC",
                    "ID",
                    "JP",
                    "TH",
                    "VN",
                    "RO",
                    "IL",
                    "ZA",
                    "SA",
                    "AE",
                    "BH",
                    "QA",
                    "OM",
                    "KW",
                    "EG",
                    "MA",
                    "DZ",
                    "TN",
                    "LB",
                    "JO",
                    "PS",
                    "IN",
                    "KZ",
                    "MD",
                    "UA",
                    "AL",
                    "BA",
                    "HR",
                    "ME",
                    "MK",
                    "RS",
                    "SI",
                    "KR",
                    "BD",
                    "PK",
                    "LK",
                    "GH",
                    "KE",
                    "NG",
                    "TZ",
                    "UG",
                    "AG",
                    "AM",
                    "BS",
                    "BB",
                    "BZ",
                    "BT",
                    "BW",
                    "BF",
                    "CV",
                    "CW",
                    "DM",
                    "FJ",
                    "GM",
                    "GE",
                    "GD",
                    "GW",
                    "GY",
                    "HT",
                    "JM",
                    "KI",
                    "LS",
                    "LR",
                    "MW",
                    "MV",
                    "ML",
                    "MH",
                    "FM",
                    "NA",
                    "NR",
                    "NE",
                    "PW",
                    "PG",
                    "WS",
                    "SM",
                    "ST",
                    "SN",
                    "SC",
                    "SL",
                    "SB",
                    "KN",
                    "LC",
                    "VC",
                    "SR",
                    "TL",
                    "TO",
                    "TT",
                    "TV",
                    "VU",
                    "AZ",
                    "BN",
                    "BI",
                    "KH",
                    "CM",
                    "TD",
                    "KM",
                    "GQ",
                    "SZ",
                    "GA",
                    "GN",
                    "KG",
                    "LA",
                    "MO",
                    "MR",
                    "MN",
                    "NP",
                    "RW",
                    "TG",
                    "UZ",
                    "ZW",
                    "BJ",
                    "MG",
                    "MU",
                    "MZ",
                    "AO",
                    "CI",
                    "DJ",
                    "ZM",
                    "CD",
                    "CG",
                    "IQ",
                    "LY",
                    "TJ",
                    "VE",
                    "ET",
                    "XK",
                ],
                "external_urls": {
                    "spotify": "https://open.spotify.com/album/4abdDHSZaiXkvPBlFD5cnv"
                },
                "href": "https://api.spotify.com/v1/albums/4abdDHSZaiXkvPBlFD5cnv",
                "id": "4abdDHSZaiXkvPBlFD5cnv",
                "images": [
                    {
                        "url": "https://i.scdn.co/image/ab67616d0000b2739edf8855e6b1b876281d65f1",
                        "width": 640,
                        "height": 640,
                    },
                    {
                        "url": "https://i.scdn.co/image/ab67616d00001e029edf8855e6b1b876281d65f1",
                        "width": 300,
                        "height": 300,
                    },
                    {
                        "url": "https://i.scdn.co/image/ab67616d000048519edf8855e6b1b876281d65f1",
                        "width": 64,
                        "height": 64,
                    },
                ],
                "name": "grünewürfelflow",
                "release_date": "2025-04-30",
                "release_date_precision": "day",
                "total_tracks": 7,
                "type": "album",
                "uri": "spotify:album:4abdDHSZaiXkvPBlFD5cnv",
            },
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/34LetYSjEuG2fBb4Z8PwPg"
                    },
                    "href": "https://api.spotify.com/v1/artists/34LetYSjEuG2fBb4Z8PwPg",
                    "id": "34LetYSjEuG2fBb4Z8PwPg",
                    "name": "Pashanim",
                    "type": "artist",
                    "uri": "spotify:artist:34LetYSjEuG2fBb4Z8PwPg",
                }
            ],
            "available_markets": [
                "AR",
                "AU",
                "AT",
                "BE",
                "BO",
                "BR",
                "BG",
                "CA",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DK",
                "DO",
                "DE",
                "EC",
                "EE",
                "SV",
                "FI",
                "FR",
                "GR",
                "GT",
                "HN",
                "HK",
                "HU",
                "IS",
                "IE",
                "IT",
                "LV",
                "LT",
                "LU",
                "MY",
                "MT",
                "MX",
                "NL",
                "NZ",
                "NI",
                "NO",
                "PA",
                "PY",
                "PE",
                "PH",
                "PL",
                "PT",
                "SG",
                "SK",
                "ES",
                "SE",
                "CH",
                "TW",
                "TR",
                "UY",
                "US",
                "GB",
                "AD",
                "LI",
                "MC",
                "ID",
                "JP",
                "TH",
                "VN",
                "RO",
                "IL",
                "ZA",
                "SA",
                "AE",
                "BH",
                "QA",
                "OM",
                "KW",
                "EG",
                "MA",
                "DZ",
                "TN",
                "LB",
                "JO",
                "PS",
                "IN",
                "KZ",
                "MD",
                "UA",
                "AL",
                "BA",
                "HR",
                "ME",
                "MK",
                "RS",
                "SI",
                "KR",
                "BD",
                "PK",
                "LK",
                "GH",
                "KE",
                "NG",
                "TZ",
                "UG",
                "AG",
                "AM",
                "BS",
                "BB",
                "BZ",
                "BT",
                "BW",
                "BF",
                "CV",
                "CW",
                "DM",
                "FJ",
                "GM",
                "GE",
                "GD",
                "GW",
                "GY",
                "HT",
                "JM",
                "KI",
                "LS",
                "LR",
                "MW",
                "MV",
                "ML",
                "MH",
                "FM",
                "NA",
                "NR",
                "NE",
                "PW",
                "PG",
                "WS",
                "SM",
                "ST",
                "SN",
                "SC",
                "SL",
                "SB",
                "KN",
                "LC",
                "VC",
                "SR",
                "TL",
                "TO",
                "TT",
                "TV",
                "VU",
                "AZ",
                "BN",
                "BI",
                "KH",
                "CM",
                "TD",
                "KM",
                "GQ",
                "SZ",
                "GA",
                "GN",
                "KG",
                "LA",
                "MO",
                "MR",
                "MN",
                "NP",
                "RW",
                "TG",
                "UZ",
                "ZW",
                "BJ",
                "MG",
                "MU",
                "MZ",
                "AO",
                "CI",
                "DJ",
                "ZM",
                "CD",
                "CG",
                "IQ",
                "LY",
                "TJ",
                "VE",
                "ET",
                "XK",
            ],
            "disc_number": 1,
            "duration_ms": 114098,
            "explicit": False,
            "external_ids": {"isrc": "DECE72501243"},
            "external_urls": {
                "spotify": "https://open.spotify.com/track/7L3Pw4DFV4vsNOAj08pfCI"
            },
            "href": "https://api.spotify.com/v1/tracks/7L3Pw4DFV4vsNOAj08pfCI",
            "id": "7L3Pw4DFV4vsNOAj08pfCI",
            "is_local": False,
            "name": "2 Sitza",
            "popularity": 79,
            "preview_url": None,
            "track_number": 2,
            "type": "track",
            "uri": "spotify:track:7L3Pw4DFV4vsNOAj08pfCI",
        }

    def _get_search_response(self):
        return {
            "tracks": {
                "href": "https://api.spotify.com/v1/search?offset=0&limit=4&query=Hallo&type=track&locale=de-DE,de;q%3D0.9,en-US;q%3D0.8,en;q%3D0.7",
                "limit": 4,
                "next": "https://api.spotify.com/v1/search?offset=4&limit=4&query=Hallo&type=track&locale=de-DE,de;q%3D0.9,en-US;q%3D0.8,en;q%3D0.7",
                "offset": 0,
                "previous": None,
                "total": 124,
                "items": [
                    {
                        "album": {
                            "album_type": "single",
                            "artists": [
                                {
                                    "external_urls": {
                                        "spotify": "https://open.spotify.com/artist/4H9W4cb3X0qRpv87yKV7fV"
                                    },
                                    "href": "https://api.spotify.com/v1/artists/4H9W4cb3X0qRpv87yKV7fV",
                                    "id": "4H9W4cb3X0qRpv87yKV7fV",
                                    "name": "Kwam.E",
                                    "type": "artist",
                                    "uri": "spotify:artist:4H9W4cb3X0qRpv87yKV7fV",
                                },
                                {
                                    "external_urls": {
                                        "spotify": "https://open.spotify.com/artist/42RwQlOWDVzGRQVa61O8VV"
                                    },
                                    "href": "https://api.spotify.com/v1/artists/42RwQlOWDVzGRQVa61O8VV",
                                    "id": "42RwQlOWDVzGRQVa61O8VV",
                                    "name": "OVE",
                                    "type": "artist",
                                    "uri": "spotify:artist:42RwQlOWDVzGRQVa61O8VV",
                                },
                            ],
                            "available_markets": [
                                "AR",
                                "AU",
                                "AT",
                                "BE",
                                "BO",
                                "BR",
                                "BG",
                                "CA",
                                "CL",
                                "CO",
                                "CR",
                                "CY",
                                "CZ",
                                "DK",
                                "DO",
                                "DE",
                                "EC",
                                "EE",
                                "SV",
                                "FI",
                                "FR",
                                "GR",
                                "GT",
                                "HN",
                                "HK",
                                "HU",
                                "IS",
                                "IE",
                                "IT",
                                "LV",
                                "LT",
                                "LU",
                                "MY",
                                "MT",
                                "MX",
                                "NL",
                                "NZ",
                                "NI",
                                "NO",
                                "PA",
                                "PY",
                                "PE",
                                "PH",
                                "PL",
                                "PT",
                                "SG",
                                "SK",
                                "ES",
                                "SE",
                                "CH",
                                "TW",
                                "TR",
                                "UY",
                                "US",
                                "GB",
                                "AD",
                                "LI",
                                "MC",
                                "ID",
                                "JP",
                                "TH",
                                "VN",
                                "RO",
                                "IL",
                                "ZA",
                                "SA",
                                "AE",
                                "BH",
                                "QA",
                                "OM",
                                "KW",
                                "EG",
                                "MA",
                                "DZ",
                                "TN",
                                "LB",
                                "JO",
                                "PS",
                                "IN",
                                "KZ",
                                "MD",
                                "UA",
                                "AL",
                                "BA",
                                "HR",
                                "ME",
                                "MK",
                                "RS",
                                "SI",
                                "KR",
                                "BD",
                                "PK",
                                "LK",
                                "GH",
                                "KE",
                                "NG",
                                "TZ",
                                "UG",
                                "AG",
                                "AM",
                                "BS",
                                "BB",
                                "BZ",
                                "BT",
                                "BW",
                                "BF",
                                "CV",
                                "CW",
                                "DM",
                                "FJ",
                                "GM",
                                "GE",
                                "GD",
                                "GW",
                                "GY",
                                "HT",
                                "JM",
                                "KI",
                                "LS",
                                "LR",
                                "MW",
                                "MV",
                                "ML",
                                "MH",
                                "FM",
                                "NA",
                                "NR",
                                "NE",
                                "PW",
                                "PG",
                                "WS",
                                "SM",
                                "ST",
                                "SN",
                                "SC",
                                "SL",
                                "SB",
                                "KN",
                                "LC",
                                "VC",
                                "SR",
                                "TL",
                                "TO",
                                "TT",
                                "TV",
                                "VU",
                                "AZ",
                                "BN",
                                "BI",
                                "KH",
                                "CM",
                                "TD",
                                "KM",
                                "GQ",
                                "SZ",
                                "GA",
                                "GN",
                                "KG",
                                "LA",
                                "MO",
                                "MR",
                                "MN",
                                "NP",
                                "RW",
                                "TG",
                                "UZ",
                                "ZW",
                                "BJ",
                                "MG",
                                "MU",
                                "MZ",
                                "AO",
                                "CI",
                                "DJ",
                                "ZM",
                                "CD",
                                "CG",
                                "IQ",
                                "LY",
                                "TJ",
                                "VE",
                                "ET",
                                "XK",
                            ],
                            "external_urls": {
                                "spotify": "https://open.spotify.com/album/2xsLhRzerB4ovi3Sx8T7Gy"
                            },
                            "href": "https://api.spotify.com/v1/albums/2xsLhRzerB4ovi3Sx8T7Gy",
                            "id": "2xsLhRzerB4ovi3Sx8T7Gy",
                            "images": [
                                {
                                    "height": 640,
                                    "width": 640,
                                    "url": "https://i.scdn.co/image/ab67616d0000b27369729c6e325f837cd94f3b0d",
                                },
                                {
                                    "height": 300,
                                    "width": 300,
                                    "url": "https://i.scdn.co/image/ab67616d00001e0269729c6e325f837cd94f3b0d",
                                },
                                {
                                    "height": 64,
                                    "width": 64,
                                    "url": "https://i.scdn.co/image/ab67616d0000485169729c6e325f837cd94f3b0d",
                                },
                            ],
                            "is_playable": True,
                            "name": "Hallow Kitty",
                            "release_date": "2023-03-03",
                            "release_date_precision": "day",
                            "total_tracks": 1,
                            "type": "album",
                            "uri": "spotify:album:2xsLhRzerB4ovi3Sx8T7Gy",
                        },
                        "artists": [
                            {
                                "external_urls": {
                                    "spotify": "https://open.spotify.com/artist/4H9W4cb3X0qRpv87yKV7fV"
                                },
                                "href": "https://api.spotify.com/v1/artists/4H9W4cb3X0qRpv87yKV7fV",
                                "id": "4H9W4cb3X0qRpv87yKV7fV",
                                "name": "Kwam.E",
                                "type": "artist",
                                "uri": "spotify:artist:4H9W4cb3X0qRpv87yKV7fV",
                            },
                            {
                                "external_urls": {
                                    "spotify": "https://open.spotify.com/artist/42RwQlOWDVzGRQVa61O8VV"
                                },
                                "href": "https://api.spotify.com/v1/artists/42RwQlOWDVzGRQVa61O8VV",
                                "id": "42RwQlOWDVzGRQVa61O8VV",
                                "name": "OVE",
                                "type": "artist",
                                "uri": "spotify:artist:42RwQlOWDVzGRQVa61O8VV",
                            },
                        ],
                        "available_markets": [
                            "AR",
                            "AU",
                            "AT",
                            "BE",
                            "BO",
                            "BR",
                            "BG",
                            "CA",
                            "CL",
                            "CO",
                            "CR",
                            "CY",
                            "CZ",
                            "DK",
                            "DO",
                            "DE",
                            "EC",
                            "EE",
                            "SV",
                            "FI",
                            "FR",
                            "GR",
                            "GT",
                            "HN",
                            "HK",
                            "HU",
                            "IS",
                            "IE",
                            "IT",
                            "LV",
                            "LT",
                            "LU",
                            "MY",
                            "MT",
                            "MX",
                            "NL",
                            "NZ",
                            "NI",
                            "NO",
                            "PA",
                            "PY",
                            "PE",
                            "PH",
                            "PL",
                            "PT",
                            "SG",
                            "SK",
                            "ES",
                            "SE",
                            "CH",
                            "TW",
                            "TR",
                            "UY",
                            "US",
                            "GB",
                            "AD",
                            "LI",
                            "MC",
                            "ID",
                            "JP",
                            "TH",
                            "VN",
                            "RO",
                            "IL",
                            "ZA",
                            "SA",
                            "AE",
                            "BH",
                            "QA",
                            "OM",
                            "KW",
                            "EG",
                            "MA",
                            "DZ",
                            "TN",
                            "LB",
                            "JO",
                            "PS",
                            "IN",
                            "KZ",
                            "MD",
                            "UA",
                            "AL",
                            "BA",
                            "HR",
                            "ME",
                            "MK",
                            "RS",
                            "SI",
                            "KR",
                            "BD",
                            "PK",
                            "LK",
                            "GH",
                            "KE",
                            "NG",
                            "TZ",
                            "UG",
                            "AG",
                            "AM",
                            "BS",
                            "BB",
                            "BZ",
                            "BT",
                            "BW",
                            "BF",
                            "CV",
                            "CW",
                            "DM",
                            "FJ",
                            "GM",
                            "GE",
                            "GD",
                            "GW",
                            "GY",
                            "HT",
                            "JM",
                            "KI",
                            "LS",
                            "LR",
                            "MW",
                            "MV",
                            "ML",
                            "MH",
                            "FM",
                            "NA",
                            "NR",
                            "NE",
                            "PW",
                            "PG",
                            "WS",
                            "SM",
                            "ST",
                            "SN",
                            "SC",
                            "SL",
                            "SB",
                            "KN",
                            "LC",
                            "VC",
                            "SR",
                            "TL",
                            "TO",
                            "TT",
                            "TV",
                            "VU",
                            "AZ",
                            "BN",
                            "BI",
                            "KH",
                            "CM",
                            "TD",
                            "KM",
                            "GQ",
                            "SZ",
                            "GA",
                            "GN",
                            "KG",
                            "LA",
                            "MO",
                            "MR",
                            "MN",
                            "NP",
                            "RW",
                            "TG",
                            "UZ",
                            "ZW",
                            "BJ",
                            "MG",
                            "MU",
                            "MZ",
                            "AO",
                            "CI",
                            "DJ",
                            "ZM",
                            "CD",
                            "CG",
                            "IQ",
                            "LY",
                            "TJ",
                            "VE",
                            "ET",
                            "XK",
                        ],
                        "disc_number": 1,
                        "duration_ms": 207428,
                        "explicit": True,
                        "external_ids": {"isrc": "CH7812346538"},
                        "external_urls": {
                            "spotify": "https://open.spotify.com/track/6sizQj16amSoj5iXMDCx5J"
                        },
                        "href": "https://api.spotify.com/v1/tracks/6sizQj16amSoj5iXMDCx5J",
                        "id": "6sizQj16amSoj5iXMDCx5J",
                        "is_local": False,
                        "is_playable": True,
                        "name": "Hallow Kitty",
                        "popularity": 62,
                        "preview_url": None,
                        "track_number": 1,
                        "type": "track",
                        "uri": "spotify:track:6sizQj16amSoj5iXMDCx5J",
                    },
                    {
                        "album": {
                            "album_type": "album",
                            "artists": [
                                {
                                    "external_urls": {
                                        "spotify": "https://open.spotify.com/artist/78TTCmh2koperK5NBn7DgR"
                                    },
                                    "href": "https://api.spotify.com/v1/artists/78TTCmh2koperK5NBn7DgR",
                                    "id": "78TTCmh2koperK5NBn7DgR",
                                    "name": "102 Boyz",
                                    "type": "artist",
                                    "uri": "spotify:artist:78TTCmh2koperK5NBn7DgR",
                                }
                            ],
                            "available_markets": [
                                "AR",
                                "AU",
                                "AT",
                                "BE",
                                "BO",
                                "BR",
                                "BG",
                                "CA",
                                "CL",
                                "CO",
                                "CR",
                                "CY",
                                "CZ",
                                "DK",
                                "DO",
                                "DE",
                                "EC",
                                "EE",
                                "SV",
                                "FI",
                                "FR",
                                "GR",
                                "GT",
                                "HN",
                                "HK",
                                "HU",
                                "IS",
                                "IE",
                                "IT",
                                "LV",
                                "LT",
                                "LU",
                                "MY",
                                "MT",
                                "MX",
                                "NL",
                                "NZ",
                                "NI",
                                "NO",
                                "PA",
                                "PY",
                                "PE",
                                "PH",
                                "PL",
                                "PT",
                                "SG",
                                "SK",
                                "ES",
                                "SE",
                                "CH",
                                "TW",
                                "TR",
                                "UY",
                                "US",
                                "GB",
                                "AD",
                                "LI",
                                "MC",
                                "ID",
                                "JP",
                                "TH",
                                "VN",
                                "RO",
                                "IL",
                                "ZA",
                                "SA",
                                "AE",
                                "BH",
                                "QA",
                                "OM",
                                "KW",
                                "EG",
                                "MA",
                                "DZ",
                                "TN",
                                "LB",
                                "JO",
                                "PS",
                                "IN",
                                "BY",
                                "KZ",
                                "MD",
                                "UA",
                                "AL",
                                "BA",
                                "HR",
                                "ME",
                                "MK",
                                "RS",
                                "SI",
                                "KR",
                                "BD",
                                "PK",
                                "LK",
                                "GH",
                                "KE",
                                "NG",
                                "TZ",
                                "UG",
                                "AG",
                                "AM",
                                "BS",
                                "BB",
                                "BZ",
                                "BT",
                                "BW",
                                "BF",
                                "CV",
                                "CW",
                                "DM",
                                "FJ",
                                "GM",
                                "GE",
                                "GD",
                                "GW",
                                "GY",
                                "HT",
                                "JM",
                                "KI",
                                "LS",
                                "LR",
                                "MW",
                                "MV",
                                "ML",
                                "MH",
                                "FM",
                                "NA",
                                "NR",
                                "NE",
                                "PW",
                                "PG",
                                "WS",
                                "SM",
                                "ST",
                                "SN",
                                "SC",
                                "SL",
                                "SB",
                                "KN",
                                "LC",
                                "VC",
                                "SR",
                                "TL",
                                "TO",
                                "TT",
                                "TV",
                                "VU",
                                "AZ",
                                "BN",
                                "BI",
                                "KH",
                                "CM",
                                "TD",
                                "KM",
                                "GQ",
                                "SZ",
                                "GA",
                                "GN",
                                "KG",
                                "LA",
                                "MO",
                                "MR",
                                "MN",
                                "NP",
                                "RW",
                                "TG",
                                "UZ",
                                "ZW",
                                "BJ",
                                "MG",
                                "MU",
                                "MZ",
                                "AO",
                                "CI",
                                "DJ",
                                "ZM",
                                "CD",
                                "CG",
                                "IQ",
                                "LY",
                                "TJ",
                                "VE",
                                "ET",
                                "XK",
                            ],
                            "external_urls": {
                                "spotify": "https://open.spotify.com/album/3bZQh8nPjo1Fk5UpKHFkTE"
                            },
                            "href": "https://api.spotify.com/v1/albums/3bZQh8nPjo1Fk5UpKHFkTE",
                            "id": "3bZQh8nPjo1Fk5UpKHFkTE",
                            "images": [
                                {
                                    "height": 640,
                                    "width": 640,
                                    "url": "https://i.scdn.co/image/ab67616d0000b273e25eea1cf6b5da7d5dcc1c0a",
                                },
                                {
                                    "height": 300,
                                    "width": 300,
                                    "url": "https://i.scdn.co/image/ab67616d00001e02e25eea1cf6b5da7d5dcc1c0a",
                                },
                                {
                                    "height": 64,
                                    "width": 64,
                                    "url": "https://i.scdn.co/image/ab67616d00004851e25eea1cf6b5da7d5dcc1c0a",
                                },
                            ],
                            "is_playable": True,
                            "name": "Asozial Allstars 1",
                            "release_date": "2018-11-02",
                            "release_date_precision": "day",
                            "total_tracks": 15,
                            "type": "album",
                            "uri": "spotify:album:3bZQh8nPjo1Fk5UpKHFkTE",
                        },
                        "artists": [
                            {
                                "external_urls": {
                                    "spotify": "https://open.spotify.com/artist/78TTCmh2koperK5NBn7DgR"
                                },
                                "href": "https://api.spotify.com/v1/artists/78TTCmh2koperK5NBn7DgR",
                                "id": "78TTCmh2koperK5NBn7DgR",
                                "name": "102 Boyz",
                                "type": "artist",
                                "uri": "spotify:artist:78TTCmh2koperK5NBn7DgR",
                            }
                        ],
                        "available_markets": [
                            "AR",
                            "AU",
                            "AT",
                            "BE",
                            "BO",
                            "BR",
                            "BG",
                            "CA",
                            "CL",
                            "CO",
                            "CR",
                            "CY",
                            "CZ",
                            "DK",
                            "DO",
                            "DE",
                            "EC",
                            "EE",
                            "SV",
                            "FI",
                            "FR",
                            "GR",
                            "GT",
                            "HN",
                            "HK",
                            "HU",
                            "IS",
                            "IE",
                            "IT",
                            "LV",
                            "LT",
                            "LU",
                            "MY",
                            "MT",
                            "MX",
                            "NL",
                            "NZ",
                            "NI",
                            "NO",
                            "PA",
                            "PY",
                            "PE",
                            "PH",
                            "PL",
                            "PT",
                            "SG",
                            "SK",
                            "ES",
                            "SE",
                            "CH",
                            "TW",
                            "TR",
                            "UY",
                            "US",
                            "GB",
                            "AD",
                            "LI",
                            "MC",
                            "ID",
                            "JP",
                            "TH",
                            "VN",
                            "RO",
                            "IL",
                            "ZA",
                            "SA",
                            "AE",
                            "BH",
                            "QA",
                            "OM",
                            "KW",
                            "EG",
                            "MA",
                            "DZ",
                            "TN",
                            "LB",
                            "JO",
                            "PS",
                            "IN",
                            "BY",
                            "KZ",
                            "MD",
                            "UA",
                            "AL",
                            "BA",
                            "HR",
                            "ME",
                            "MK",
                            "RS",
                            "SI",
                            "KR",
                            "BD",
                            "PK",
                            "LK",
                            "GH",
                            "KE",
                            "NG",
                            "TZ",
                            "UG",
                            "AG",
                            "AM",
                            "BS",
                            "BB",
                            "BZ",
                            "BT",
                            "BW",
                            "BF",
                            "CV",
                            "CW",
                            "DM",
                            "FJ",
                            "GM",
                            "GE",
                            "GD",
                            "GW",
                            "GY",
                            "HT",
                            "JM",
                            "KI",
                            "LS",
                            "LR",
                            "MW",
                            "MV",
                            "ML",
                            "MH",
                            "FM",
                            "NA",
                            "NR",
                            "NE",
                            "PW",
                            "PG",
                            "WS",
                            "SM",
                            "ST",
                            "SN",
                            "SC",
                            "SL",
                            "SB",
                            "KN",
                            "LC",
                            "VC",
                            "SR",
                            "TL",
                            "TO",
                            "TT",
                            "TV",
                            "VU",
                            "AZ",
                            "BN",
                            "BI",
                            "KH",
                            "CM",
                            "TD",
                            "KM",
                            "GQ",
                            "SZ",
                            "GA",
                            "GN",
                            "KG",
                            "LA",
                            "MO",
                            "MR",
                            "MN",
                            "NP",
                            "RW",
                            "TG",
                            "UZ",
                            "ZW",
                            "BJ",
                            "MG",
                            "MU",
                            "MZ",
                            "AO",
                            "CI",
                            "DJ",
                            "ZM",
                            "CD",
                            "CG",
                            "IQ",
                            "LY",
                            "TJ",
                            "VE",
                            "ET",
                            "XK",
                        ],
                        "disc_number": 1,
                        "duration_ms": 166285,
                        "explicit": True,
                        "external_ids": {"isrc": "DEVX51800013"},
                        "external_urls": {
                            "spotify": "https://open.spotify.com/track/4ITNWPTWB3SKQgveGsA9A9"
                        },
                        "href": "https://api.spotify.com/v1/tracks/4ITNWPTWB3SKQgveGsA9A9",
                        "id": "4ITNWPTWB3SKQgveGsA9A9",
                        "is_local": False,
                        "is_playable": True,
                        "name": "Hallo",
                        "popularity": 44,
                        "preview_url": None,
                        "track_number": 4,
                        "type": "track",
                        "uri": "spotify:track:4ITNWPTWB3SKQgveGsA9A9",
                    },
                    {
                        "album": {
                            "album_type": "album",
                            "artists": [
                                {
                                    "external_urls": {
                                        "spotify": "https://open.spotify.com/artist/4bId6MR2fskVKIeCSEmktg"
                                    },
                                    "href": "https://api.spotify.com/v1/artists/4bId6MR2fskVKIeCSEmktg",
                                    "id": "4bId6MR2fskVKIeCSEmktg",
                                    "name": "Ivo Martin",
                                    "type": "artist",
                                    "uri": "spotify:artist:4bId6MR2fskVKIeCSEmktg",
                                }
                            ],
                            "available_markets": [
                                "AR",
                                "AU",
                                "AT",
                                "BE",
                                "BO",
                                "BR",
                                "BG",
                                "CA",
                                "CL",
                                "CO",
                                "CR",
                                "CY",
                                "CZ",
                                "DK",
                                "DO",
                                "DE",
                                "EC",
                                "EE",
                                "SV",
                                "FI",
                                "FR",
                                "GR",
                                "GT",
                                "HN",
                                "HK",
                                "HU",
                                "IS",
                                "IE",
                                "IT",
                                "LV",
                                "LT",
                                "LU",
                                "MY",
                                "MT",
                                "MX",
                                "NL",
                                "NZ",
                                "NI",
                                "NO",
                                "PA",
                                "PY",
                                "PE",
                                "PH",
                                "PL",
                                "PT",
                                "SG",
                                "SK",
                                "ES",
                                "SE",
                                "CH",
                                "TW",
                                "TR",
                                "UY",
                                "US",
                                "GB",
                                "AD",
                                "LI",
                                "MC",
                                "ID",
                                "JP",
                                "TH",
                                "VN",
                                "RO",
                                "IL",
                                "ZA",
                                "SA",
                                "AE",
                                "BH",
                                "QA",
                                "OM",
                                "KW",
                                "EG",
                                "MA",
                                "DZ",
                                "TN",
                                "LB",
                                "JO",
                                "PS",
                                "IN",
                                "BY",
                                "KZ",
                                "MD",
                                "UA",
                                "AL",
                                "BA",
                                "HR",
                                "ME",
                                "MK",
                                "RS",
                                "SI",
                                "KR",
                                "BD",
                                "PK",
                                "LK",
                                "GH",
                                "KE",
                                "NG",
                                "TZ",
                                "UG",
                                "AG",
                                "AM",
                                "BS",
                                "BB",
                                "BZ",
                                "BT",
                                "BW",
                                "BF",
                                "CV",
                                "CW",
                                "DM",
                                "FJ",
                                "GM",
                                "GE",
                                "GD",
                                "GW",
                                "GY",
                                "HT",
                                "JM",
                                "KI",
                                "LS",
                                "LR",
                                "MW",
                                "MV",
                                "ML",
                                "MH",
                                "FM",
                                "NA",
                                "NR",
                                "NE",
                                "PW",
                                "PG",
                                "PR",
                                "WS",
                                "SM",
                                "ST",
                                "SN",
                                "SC",
                                "SL",
                                "SB",
                                "KN",
                                "LC",
                                "VC",
                                "SR",
                                "TL",
                                "TO",
                                "TT",
                                "TV",
                                "VU",
                                "AZ",
                                "BN",
                                "BI",
                                "KH",
                                "CM",
                                "TD",
                                "KM",
                                "GQ",
                                "SZ",
                                "GA",
                                "GN",
                                "KG",
                                "LA",
                                "MO",
                                "MR",
                                "MN",
                                "NP",
                                "RW",
                                "TG",
                                "UZ",
                                "ZW",
                                "BJ",
                                "MG",
                                "MU",
                                "MZ",
                                "AO",
                                "CI",
                                "DJ",
                                "ZM",
                                "CD",
                                "CG",
                                "IQ",
                                "LY",
                                "TJ",
                                "VE",
                                "ET",
                                "XK",
                            ],
                            "external_urls": {
                                "spotify": "https://open.spotify.com/album/1kvNSkYhcc6oKkxzyINAQn"
                            },
                            "href": "https://api.spotify.com/v1/albums/1kvNSkYhcc6oKkxzyINAQn",
                            "id": "1kvNSkYhcc6oKkxzyINAQn",
                            "images": [
                                {
                                    "height": 640,
                                    "width": 640,
                                    "url": "https://i.scdn.co/image/ab67616d0000b273d0d0c3685a1509df11e4c933",
                                },
                                {
                                    "height": 300,
                                    "width": 300,
                                    "url": "https://i.scdn.co/image/ab67616d00001e02d0d0c3685a1509df11e4c933",
                                },
                                {
                                    "height": 64,
                                    "width": 64,
                                    "url": "https://i.scdn.co/image/ab67616d00004851d0d0c3685a1509df11e4c933",
                                },
                            ],
                            "is_playable": True,
                            "name": "Weit weg Tape",
                            "release_date": "2023-07-07",
                            "release_date_precision": "day",
                            "total_tracks": 7,
                            "type": "album",
                            "uri": "spotify:album:1kvNSkYhcc6oKkxzyINAQn",
                        },
                        "artists": [
                            {
                                "external_urls": {
                                    "spotify": "https://open.spotify.com/artist/4bId6MR2fskVKIeCSEmktg"
                                },
                                "href": "https://api.spotify.com/v1/artists/4bId6MR2fskVKIeCSEmktg",
                                "id": "4bId6MR2fskVKIeCSEmktg",
                                "name": "Ivo Martin",
                                "type": "artist",
                                "uri": "spotify:artist:4bId6MR2fskVKIeCSEmktg",
                            }
                        ],
                        "available_markets": [
                            "AR",
                            "AU",
                            "AT",
                            "BE",
                            "BO",
                            "BR",
                            "BG",
                            "CA",
                            "CL",
                            "CO",
                            "CR",
                            "CY",
                            "CZ",
                            "DK",
                            "DO",
                            "DE",
                            "EC",
                            "EE",
                            "SV",
                            "FI",
                            "FR",
                            "GR",
                            "GT",
                            "HN",
                            "HK",
                            "HU",
                            "IS",
                            "IE",
                            "IT",
                            "LV",
                            "LT",
                            "LU",
                            "MY",
                            "MT",
                            "MX",
                            "NL",
                            "NZ",
                            "NI",
                            "NO",
                            "PA",
                            "PY",
                            "PE",
                            "PH",
                            "PL",
                            "PT",
                            "SG",
                            "SK",
                            "ES",
                            "SE",
                            "CH",
                            "TW",
                            "TR",
                            "UY",
                            "US",
                            "GB",
                            "AD",
                            "LI",
                            "MC",
                            "ID",
                            "JP",
                            "TH",
                            "VN",
                            "RO",
                            "IL",
                            "ZA",
                            "SA",
                            "AE",
                            "BH",
                            "QA",
                            "OM",
                            "KW",
                            "EG",
                            "MA",
                            "DZ",
                            "TN",
                            "LB",
                            "JO",
                            "PS",
                            "IN",
                            "BY",
                            "KZ",
                            "MD",
                            "UA",
                            "AL",
                            "BA",
                            "HR",
                            "ME",
                            "MK",
                            "RS",
                            "SI",
                            "KR",
                            "BD",
                            "PK",
                            "LK",
                            "GH",
                            "KE",
                            "NG",
                            "TZ",
                            "UG",
                            "AG",
                            "AM",
                            "BS",
                            "BB",
                            "BZ",
                            "BT",
                            "BW",
                            "BF",
                            "CV",
                            "CW",
                            "DM",
                            "FJ",
                            "GM",
                            "GE",
                            "GD",
                            "GW",
                            "GY",
                            "HT",
                            "JM",
                            "KI",
                            "LS",
                            "LR",
                            "MW",
                            "MV",
                            "ML",
                            "MH",
                            "FM",
                            "NA",
                            "NR",
                            "NE",
                            "PW",
                            "PG",
                            "PR",
                            "WS",
                            "SM",
                            "ST",
                            "SN",
                            "SC",
                            "SL",
                            "SB",
                            "KN",
                            "LC",
                            "VC",
                            "SR",
                            "TL",
                            "TO",
                            "TT",
                            "TV",
                            "VU",
                            "AZ",
                            "BN",
                            "BI",
                            "KH",
                            "CM",
                            "TD",
                            "KM",
                            "GQ",
                            "SZ",
                            "GA",
                            "GN",
                            "KG",
                            "LA",
                            "MO",
                            "MR",
                            "MN",
                            "NP",
                            "RW",
                            "TG",
                            "UZ",
                            "ZW",
                            "BJ",
                            "MG",
                            "MU",
                            "MZ",
                            "AO",
                            "CI",
                            "DJ",
                            "ZM",
                            "CD",
                            "CG",
                            "IQ",
                            "LY",
                            "TJ",
                            "VE",
                            "ET",
                            "XK",
                        ],
                        "disc_number": 1,
                        "duration_ms": 120732,
                        "explicit": False,
                        "external_ids": {"isrc": "DEE862300939"},
                        "external_urls": {
                            "spotify": "https://open.spotify.com/track/2xhQ4DChsw78ca8fUUZo5b"
                        },
                        "href": "https://api.spotify.com/v1/tracks/2xhQ4DChsw78ca8fUUZo5b",
                        "id": "2xhQ4DChsw78ca8fUUZo5b",
                        "is_local": False,
                        "is_playable": True,
                        "name": "Hallo",
                        "popularity": 61,
                        "preview_url": None,
                        "track_number": 1,
                        "type": "track",
                        "uri": "spotify:track:2xhQ4DChsw78ca8fUUZo5b",
                    },
                ],
            }
        }
