# Generated by Django 5.2 on 2025-06-20 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="genre",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pop", "Pop"),
                    ("Rock", "Rock"),
                    ("Hip-Hop", "Hip-Hop"),
                    ("Electronic", "Electronic"),
                    ("Jazz", "Jazz"),
                    ("Classical", "Classical"),
                    ("Indie", "Indie"),
                    ("Metal", "Metal"),
                    ("Folk", "Folk"),
                    ("Schlager", "Schlager"),
                    ("Andere", "Andere"),
                    ("Gemischt", "Gemischt"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(
                related_name="member_groups",
                through="mainapp.Membership",
                to="mainapp.usermeta",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="moderators",
            field=models.ManyToManyField(
                related_name="moderator_groups", to="mainapp.usermeta"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_groups",
                to="mainapp.usermeta",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="profile_Image",
            field=models.ImageField(blank=True, null=True, upload_to="group_images/"),
        ),
    ]
