# Generated by Django 5.2 on 2025-06-17 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FriendsCombinations",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "baseUser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendships_baseUser",
                        to="mainapp.usermeta",
                    ),
                ),
                (
                    "friend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendship_friend",
                        to="mainapp.usermeta",
                    ),
                ),
            ],
            options={
                "unique_together": {("baseUser", "friend")},
            },
        ),
    ]
