# Generated by Django 5.2 on 2025-06-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="music",
            name="spotify_id",
        ),
        migrations.AlterField(
            model_name="music",
            name="id",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
