# Generated by Django 5.2 on 2025-06-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("moderator", "Moderator"),
                    ("member", "Member"),
                    ("archive_viewer", "Archive Viewer"),
                ],
                default="member",
                max_length=30,
            ),
        ),
    ]
