# Generated by Django 5.2 on 2025-06-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_group_genre_group_members_group_moderators_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="post_permission",
            field=models.CharField(
                choices=[
                    ("all", "Alle Mitglieder"),
                    ("moderators", "Nur Moderatoren"),
                    ("owner", "Nur Besitzer"),
                ],
                default="all",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="read_permission",
            field=models.CharField(
                choices=[
                    ("all", "Alle Mitglieder"),
                    ("moderators", "Nur Moderatoren"),
                    ("owner", "Nur Besitzer"),
                ],
                default="all",
                max_length=50,
            ),
        ),
    ]
