name: test_Django
on: [pull_request, push] 
jobs:
  test_project:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r requirements.txt 
      - name: Run pytest
        run: |
          cd app
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest -v
      - name: Run ruff
        run: |
          ruff check app/

      - name: Run black
        run: |
          black --check app/
